[package]
name = "http"
version = "0.1.0"
authors = ["nixinfeng <nixinfeng@ddspace.com.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
